name: final_year_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dartx: ^1.0.0
  dartz: ^0.10.1
  dio: ^4.0.4
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: null
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.0
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  rxdart: ^0.27.3
  scan: ^1.6.0
  uuid: ^3.0.5
  web3dart: ^2.3.3

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  injectable_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/contract/abi.json
