name: final_year_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  web3dart: ^2.3.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
